apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  server_url: {{ .Values.server.url | quote }}
  cluster_name: {{ .Values.cluster.name | quote }}
