apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skyops.fullname" . }}-config
  labels:
    {{- include "skyops.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  DEPLOYMENT_MODE: {{ .Values.env.DEPLOYMENT_MODE | default "self-hosted" | quote }}
  DATA_TELEMETRY_ENABLED: {{ .Values.env.DATA_TELEMETRY_ENABLED | default "false" | quote }}
  SKYOPS_DATA_DIR: {{ .Values.persistence.mountPath | default "/app/.data" | quote }}
  APP_URL: {{ .Values.env.APP_URL | default (printf "http://%s:%d" (include "skyops.fullname" .) (int .Values.service.port)) | quote }}
  SKYOPS_SERVER_URL: {{ printf "http://%s:%d" (include "skyops.fullname" .) (int .Values.service.port) | quote }}
  SKYOPS_CLUSTER_NAME: {{ .Values.agent.clusterName | default "in-cluster" | quote }}
