apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skyops.fullname" . | default "skyops" }}-config
  labels:
    app.kubernetes.io/name: skyops
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  NODE_ENV: "production"
  DEPLOYMENT_MODE: {{ .Values.env.DEPLOYMENT_MODE | default "self-hosted" | quote }}
  DATA_TELEMETRY_ENABLED: {{ .Values.env.DATA_TELEMETRY_ENABLED | default "false" | quote }}
  APP_URL: {{ .Values.env.APP_URL | default "http://localhost:3000" | quote }}
  SKYOPS_DATA_DIR: "/app/.data"
